services:
  sph-nca:
    build: .
    volumes:
      - ./code/:/home/cgv/code
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
